<?php

namespace App\Social\Fake;

use App\Enums\ContentType;
use App\Enums\Platform;
use App\Social\Data\AccountProfile;
use App\Social\Data\AudienceInsights;
use App\Social\Data\ContentItem;
use App\Social\Data\ContentMetrics;
use App\Social\Data\ProviderIdentity;
use Carbon\CarbonImmutable;

/**
 * Deterministic fake data: the same platform + handle always yields the same account,
 * content and metrics, which keeps demos and tests stable.
 */
class FakeDataGenerator
{
    public function providerAccountId(Platform $platform, string $handle): string
    {
        $hash = sha1($platform->value.':'.strtolower($handle));

        return match ($platform) {
            Platform::YouTube => 'UC'.substr(strtr(base64_encode(hex2bin($hash)), '+/', '-_'), 0, 22),
            Platform::Instagram => '178'.substr(preg_replace('/\D/', '', $hash.crc32($hash)), 0, 14),
            Platform::X => '1'.substr(preg_replace('/\D/', '', $hash.crc32($hash)), 0, 18),
        };
    }

    public function account(Platform $platform, string $handle): array
    {
        $handle = strtolower($handle);

        if ($curated = FakeAccounts::find($platform, $handle)) {
            return $this->withDefaults($curated);
        }

        $rng = $this->rng($platform, $handle, 'account');
        $followers = (int) round($rng->between(3_000, 400_000), -2);

        return $this->withDefaults([
            'platform' => $platform,
            'handle' => $handle,
            'display_name' => ucwords(str_replace(['.', '_', '-'], ' ', $handle)),
            'followers' => $followers,
            'bio' => 'Demo account generated by the fake connector.',
        ]);
    }

    public function identity(Platform $platform, string $handle): ProviderIdentity
    {
        $account = $this->account($platform, $handle);

        return new ProviderIdentity(
            providerAccountId: $this->providerAccountId($platform, $handle),
            handle: $account['handle'],
            displayName: $account['display_name'],
            avatarUrl: $account['avatar'],
            followerCount: $account['followers'],
            raw: ['fake' => true],
        );
    }

    public function profile(Platform $platform, string $handle, bool $authenticated): AccountProfile
    {
        $account = $this->account($platform, $handle);
        $metrics = [];

        if ($authenticated) {
            $metrics = match ($platform) {
                Platform::YouTube => ['total_views' => $account['followers'] * 180, 'video_count' => array_sum(array_column($account['content'], 'count'))],
                Platform::Instagram => ['media_count' => array_sum(array_column($account['content'], 'count')) + 40],
                Platform::X => ['post_count' => $account['content']['post']['count'] * 30],
            };
        }

        return new AccountProfile(
            providerAccountId: $this->providerAccountId($platform, $handle),
            handle: $account['handle'],
            displayName: $account['display_name'],
            avatarUrl: $account['avatar'],
            followerCount: $account['followers'],
            bio: $account['bio'],
            website: null,
            metrics: $metrics,
            raw: ['fake' => true],
        );
    }

    /** @return ContentItem[] newest first */
    public function content(Platform $platform, string $handle, int $limit): array
    {
        $account = $this->account($platform, $handle);
        $items = [];

        foreach ($account['content'] as $type => $profile) {
            $contentType = ContentType::from($type);
            $rng = $this->rng($platform, $handle, "content:{$type}");
            $publishedAt = CarbonImmutable::now()->startOfDay()->subDays($rng->between(1, 4));
            $cadenceDays = $contentType === ContentType::Post || $contentType === ContentType::Short ? 2 : 6;

            for ($i = 0; $i < $profile['count']; $i++) {
                $id = $this->contentId($platform, $handle, $contentType, $i);

                $items[] = new ContentItem(
                    providerContentId: $id,
                    contentType: $contentType,
                    title: $this->title($rng, $contentType, $i),
                    url: $this->contentUrl($platform, $handle, $contentType, $id),
                    thumbnailUrl: $this->thumbnail($id, $contentType),
                    publishedAt: $publishedAt,
                    durationSeconds: match ($contentType) {
                        ContentType::Video => $rng->between(420, 1500),
                        ContentType::Short => $rng->between(20, 58),
                        ContentType::Reel => $rng->between(9, 45),
                        ContentType::Post => null,
                    },
                    metrics: [],
                    raw: ['fake' => true],
                );

                $publishedAt = $publishedAt->subDays($rng->between(1, $cadenceDays * 2));
            }
        }

        usort($items, fn (ContentItem $a, ContentItem $b) => $b->publishedAt <=> $a->publishedAt);

        return array_slice($items, 0, $limit);
    }

    /**
     * Metrics for a content item. The same item always returns the same numbers,
     * with a small deterministic drift so repeated syncs look alive.
     */
    public function metrics(Platform $platform, string $handle, ContentType $type, string $providerContentId, int $ageDays): ContentMetrics
    {
        $account = $this->account($platform, $handle);
        $profile = $account['content'][$type->value] ?? $this->defaultProfile($platform, $type, $account['followers']);
        $rng = $this->rng($platform, $handle, "metrics:{$providerContentId}");

        $factor = 1 + $rng->float(-$profile['spread'], $profile['spread']);

        if ($rng->float(0, 1) < $profile['viral_chance']) {
            $factor *= $rng->float(4, 25);
        }

        // Content keeps collecting views for a while after publishing.
        $maturity = min(1, 0.55 + $ageDays / 30);
        $views = (int) round($profile['median_views'] * $factor * $maturity);
        $engagement = $profile['engagement'] * (1 + $rng->float(-0.2, 0.2));
        $interactions = (int) round($views * $engagement);

        $metrics = match ($platform) {
            Platform::YouTube => [
                'views' => $views,
                'likes' => (int) round($interactions * 0.86),
                'comments' => (int) round($interactions * 0.09),
                'shares' => (int) round($interactions * 0.05),
                'average_view_percentage' => round($profile['view_pct'] * (1 + $rng->float(-0.12, 0.12)), 1),
                'average_watch_time_seconds' => round($profile['avg_watch'] * (1 + $rng->float(-0.15, 0.15)), 1),
            ],
            Platform::Instagram => [
                'views' => $views,
                'reach' => (int) round($views * $profile['reach_ratio'] * (1 + $rng->float(-0.08, 0.08))),
                'likes' => (int) round($interactions * 0.78),
                'comments' => (int) round($interactions * 0.05),
                'shares' => (int) round($interactions * 0.09),
                'saves' => (int) round($interactions * 0.08),
                'engagements' => $interactions,
            ] + ($type === ContentType::Reel ? [
                'average_watch_time_seconds' => round($profile['avg_watch'] * (1 + $rng->float(-0.2, 0.2)), 2),
            ] : []),
            Platform::X => [
                'impressions' => $views,
                'views' => $views,
                'likes' => (int) round($interactions * 0.62),
                'replies' => (int) round($interactions * 0.08),
                'reposts' => (int) round($interactions * 0.14),
                'bookmarks' => (int) round($interactions * 0.16),
                'engagements' => (int) round($interactions * 1.9),
                'profile_clicks' => (int) round($views * $profile['profile_click_rate']),
                'url_clicks' => (int) round($views * $profile['url_click_rate']),
            ],
        };

        if ($platform === Platform::YouTube) {
            $metrics['watch_time_seconds'] = (int) round($views * $metrics['average_watch_time_seconds']);
        }

        if ($platform === Platform::Instagram && $type === ContentType::Reel) {
            $metrics['watch_time_seconds'] = (int) round($views * $metrics['average_watch_time_seconds']);
        }

        $insights = [];

        if ($platform === Platform::YouTube) {
            $insights['retention'] = $this->retentionCurve($rng, $profile['view_pct']);
            $insights['daily_views'] = $this->dailyViews($rng, $views, $ageDays);
            $metrics['views_24h'] = $insights['daily_views'][0] ?? 0;
            $metrics['views_7d'] = array_sum(array_slice($insights['daily_views'], 0, 7));
        }

        return new ContentMetrics($providerContentId, $metrics, ['fake' => true, 'factor' => round($factor, 3)], $insights);
    }

    /**
     * Audience breakdowns. Curated accounts can pin these; otherwise they are derived from the handle.
     */
    public function audience(Platform $platform, string $handle): AudienceInsights
    {
        if ($platform === Platform::X) {
            return new AudienceInsights; // X has no audience insights API.
        }

        $account = $this->account($platform, $handle);
        $rng = $this->rng($platform, $handle, 'audience');
        $pinned = $account['audience'] ?? [];

        $age = $pinned['age'] ?? $this->distribution($rng, ['18-24' => 18, '25-34' => 38, '35-44' => 24, '45-54' => 12, '55-64' => 5, '65+' => 3]);
        $gender = $pinned['gender'] ?? $this->distribution($rng, ['male' => 55, 'female' => 44, 'user_specified' => 1]);
        $countries = $pinned['countries'] ?? $this->distribution($rng, ['US' => 34, 'GB' => 18, 'CA' => 8, 'AU' => 6, 'DE' => 5, 'IN' => 9, 'FR' => 3, 'NL' => 3, 'BR' => 3, 'JP' => 2], keepRest: 9);

        if ($platform === Platform::YouTube) {
            return new AudienceInsights(
                age: $age,
                gender: $gender,
                countries: $countries,
                devices: $pinned['devices'] ?? $this->distribution($rng, ['mobile' => 58, 'desktop' => 28, 'tv' => 10, 'tablet' => 4]),
                accountMetrics: [
                    'views_28d' => (int) round($account['followers'] * $rng->float(6, 14)),
                    'watch_time_seconds_28d' => (int) round($account['followers'] * $rng->float(2000, 5000)),
                    'subscribers_gained_28d' => (int) round($account['followers'] * $rng->float(0.01, 0.04)),
                    'subscribers_lost_28d' => (int) round($account['followers'] * $rng->float(0.002, 0.006)),
                ],
                raw: ['fake' => true],
            );
        }

        $nonFollower = $pinned['non_follower'] ?? $rng->float(35, 75);

        return new AudienceInsights(
            age: $age,
            gender: $gender,
            countries: $countries,
            cities: $pinned['cities'] ?? $this->distribution($rng, ['London' => 9, 'New York' => 7, 'Los Angeles' => 5, 'Toronto' => 4, 'Sydney' => 3], keepRest: 72),
            followerType: ['follower' => round(100 - $nonFollower, 1), 'non_follower' => round($nonFollower, 1)],
            accountMetrics: [
                'reach_30d' => (int) round($account['followers'] * $rng->float(8, 20)),
                'profile_views_30d' => (int) round($account['followers'] * $rng->float(0.15, 0.3)),
                'website_clicks_30d' => (int) round($account['followers'] * $rng->float(0.01, 0.03)),
            ],
            raw: ['fake' => true],
        );
    }

    /** 21 points, 0% → 100% of the video: a steep early drop that levels out. */
    private function retentionCurve(FakeRandom $rng, float $viewPct): array
    {
        $end = max(4, min(60, $viewPct * 0.5 * (1 + $rng->float(-0.2, 0.2))));
        $hook = max($end + 10, min(95, 60 + $viewPct * 0.55 + $rng->float(-6, 6)));
        $curve = [100.0];

        for ($i = 1; $i <= 20; $i++) {
            $t = $i / 20;
            // Exponential-ish decay from the 30-second hook value down to the end value.
            $value = $end + ($hook - $end) * exp(-3.2 * ($t - 0.05)) * (1 + $rng->float(-0.03, 0.03));
            $curve[] = round(min($curve[$i - 1], max($end, $value)), 1);
        }

        return $curve;
    }

    /** Views per day for the first 30 days: front-loaded, long tail. */
    private function dailyViews(FakeRandom $rng, int $totalViews, int $ageDays): array
    {
        $days = max(1, min(30, $ageDays + 1));
        $weights = [];

        for ($d = 0; $d < 30; $d++) {
            $weights[] = exp(-0.28 * $d) * (1 + $rng->float(-0.15, 0.15)) + 0.012;
        }

        $sum = array_sum($weights);
        $scale = $totalViews / max(1e-6, array_sum(array_slice($weights, 0, $days)) + array_sum(array_slice($weights, $days)) * 0.35);

        return array_map(fn ($w) => (int) round($w * $scale), array_slice($weights, 0, $days));
    }

    /** Jitters a base distribution and re-normalises it to 100. */
    private function distribution(FakeRandom $rng, array $base, float $keepRest = 0): array
    {
        $out = [];
        foreach ($base as $key => $weight) {
            $out[$key] = $weight * (1 + $rng->float(-0.35, 0.35));
        }
        $target = 100 - $keepRest;
        $sum = array_sum($out) ?: 1;

        return array_map(fn ($v) => round($v / $sum * $target, 1), $out);
    }

    private function withDefaults(array $account): array
    {
        $account['avatar'] ??= 'https://i.pravatar.cc/200?u='.$account['platform']->value.'-'.$account['handle'];
        $account['bio'] ??= null;

        if (empty($account['content'])) {
            $account['content'] = [];
            foreach ($account['platform']->contentTypes() as $type) {
                $account['content'][$type->value] = $this->defaultProfile($account['platform'], $type, $account['followers']);
            }
        }

        return $account;
    }

    private function defaultProfile(Platform $platform, ContentType $type, int $followers): array
    {
        $rng = $this->rng($platform, (string) $followers, 'profile:'.$type->value);
        $ratio = $rng->float(0.05, 0.6);

        return [
            'count' => $type === ContentType::Post ? 30 : 20,
            'median_views' => (int) round($followers * $ratio, -2),
            'spread' => 0.35,
            'viral_chance' => 0.05,
            'engagement' => $rng->float(0.015, 0.06),
            'view_pct' => $type === ContentType::Short ? 80 : 38,
            'avg_watch' => match ($type) {
                ContentType::Video => 300,
                ContentType::Short => 25,
                ContentType::Reel => 7,
                ContentType::Post => 0,
            },
            'reach_ratio' => 0.8,
            'profile_click_rate' => 0.008,
            'url_click_rate' => 0.004,
        ];
    }

    private function contentId(Platform $platform, string $handle, ContentType $type, int $index): string
    {
        $hash = substr(sha1("{$platform->value}:{$handle}:{$type->value}:{$index}"), 0, 16);

        return match ($platform) {
            Platform::YouTube => substr(strtr(base64_encode(hex2bin($hash)), '+/', '-_'), 0, 11),
            Platform::Instagram => '179'.substr(preg_replace('/\D/', '', $hash.crc32($hash)), 0, 14),
            Platform::X => '18'.substr(preg_replace('/\D/', '', $hash.crc32($hash)), 0, 17),
        };
    }

    private function contentUrl(Platform $platform, string $handle, ContentType $type, string $id): string
    {
        return match ($platform) {
            Platform::YouTube => ($type === ContentType::Short ? 'https://www.youtube.com/shorts/' : 'https://www.youtube.com/watch?v=').$id,
            Platform::Instagram => 'https://www.instagram.com/'.($type === ContentType::Reel ? 'reel' : 'p').'/'.substr(base64_encode($id), 0, 11).'/',
            Platform::X => "https://x.com/{$handle}/status/{$id}",
        };
    }

    private function thumbnail(string $id, ContentType $type): string
    {
        $seed = substr(md5($id), 0, 8);

        return match ($type) {
            ContentType::Video => "https://picsum.photos/seed/{$seed}/480/270",
            ContentType::Short, ContentType::Reel => "https://picsum.photos/seed/{$seed}/270/480",
            ContentType::Post => "https://picsum.photos/seed/{$seed}/400/400",
        };
    }

    private function title(FakeRandom $rng, ContentType $type, int $index): string
    {
        $subjects = ['the one thing nobody tells you', 'a week of', 'why I stopped', 'the honest truth about', 'what I learned from', 'the beginner mistake with', 'how I plan', 'a simple system for', 'the real cost of', 'my favourite'];
        $objects = ['budgeting', 'training', 'shipping', 'travel', 'cooking at home', 'studying', 'growing an audience', 'lighting', 'consistency', 'saying no', 'morning routines', 'gear', 'pricing', 'rest days'];

        $s = $subjects[$rng->between(0, count($subjects) - 1)];
        $o = $objects[$rng->between(0, count($objects) - 1)];
        $text = ucfirst("{$s} {$o}");

        return match ($type) {
            ContentType::Video => $text,
            ContentType::Short => $text.' #shorts',
            ContentType::Reel => $text.' 🎬',
            ContentType::Post => $text.'. Thread below.',
        };
    }

    private function rng(Platform $platform, string $handle, string $scope): FakeRandom
    {
        return new FakeRandom(crc32("{$platform->value}|{$handle}|{$scope}"));
    }
}
